version: '3'
services:
  isit-a-cat-backend:
    build: .
    ports:
      - "8095:8080"
    depends_on:
      - minio
    links:
      - minio
    env_file:
      - .env
    command: run backend
  isit-a-cat-bot:
    build: .
    depends_on:
      - minio
    links:
      - minio
    command: run bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
  isit-a-cat-frontend:
    build: frontend
    ports:
      - "8090:8043" 
    links:
      - isit-a-cat-backend
  minio:
    image: minio/minio
    volumes:
      - ./bucket_data:/data
    ports:
      - "9000:9000"
    env_file:
      - .env
    command: server /data
