// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageService is an autogenerated mock type for the StorageService type
type StorageServiceMock struct {
	mock.Mock
}

// WriteToBucketObject provides a mock function with given fields: objectId, data
func (_m *StorageServiceMock) WriteToBucketObject(objectId string, data []byte) error {
	ret := _m.Called(objectId, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(objectId, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
